import type { Metadata } from "next";
import "./globals.css";
import { Merriweather, Open_Sans } from "next/font/google";

const merriweather = Merriweather({ subsets: ["latin"], weight: ["400","700"] });
const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Les echos - Newsletters",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} ${openSans.className}`}>
        {children}
      </body>
    </html>
  );
}
